### ISSUE TITLE
slack_reporterのlossがNaNへの対応

### ISSUE THREAD

**Issue by hrsma2i** [tn1031/chainer-sagemaker-tools#7]
slack_reporterにおいて「urllib.error.HTTPError: HTTP Error 400: Bad Request」が出て、学習が止まってしまいました。

おそらく、原因はlossがNaNになったことだと思われます。

**Comment by tn1031** [comment]
認識していて、NaNの時は学習を止めたいので動作は結果的に意図した通りです。
エラーハンドリングは親切でないですが、後回しにしています。
